import '@/styles/globals.css';
import { ToastContainer } from 'react-toastify';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { UserProvider } from '@/contexts/user.context';
import { WebsocketProvider } from '@/contexts/websocket';

const inter = Inter({ subsets : ['latin'] });

export const metadata: Metadata = {
  title : 'Create Next App',
  description : 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {
          <UserProvider>
            <WebsocketProvider>
              <ToastContainer />
              {children}
            </WebsocketProvider>
          </UserProvider>
        }
      </body>
    </html>
  );
}
